/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   dev-lib/prepare.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

/**
 * A class that is executed when node dependencies are installed.
 */
declare class ComponentPrepare {
  run(): any;
  nodeToBrowser(file: any): any;
  uglyContent(content: any): any;
  babelify(code: any): any;
  waitFor(stream: any): any;
  copyJexl(): any;
}
